name: Github sanity scanner

on:
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  github-sanity-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Github sanity scanner
      uses: outscale/github-sanity-scan@main
      with:
        no-pull-request-target: true
